# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "Hello there,"

# This page should be the root of your website. It's important.
page = "https://ink-chartreuse-32c.notion.site/Hello-There-bbddaa12a12b48a38c8af9b22be29c82?pvs=4"
